### ISSUE TITLE
error: No module named 'packaging'

### ISSUE THREAD

**Issue by jpriebe** [abij/az-account-switcher#3]
Running on MacOS 11.3.1 with python 3.9 installed via homebrew.

az-switch works; it displays the menu, and it sets the subscription.  But when it closes, it outputs:

    No module named 'packaging'

A `pip install packaging` fixed it, but maybe there is some kind of dependency that needs to be added to the `az-account-switcher` package?

Great utility, btw.  Reminds me of kubectx and kubens (https://github.com/ahmetb/kubectx).

**Comment by abij** [comment]
Checked with `pipdeptree --reverse --packages packaging`.

I'll switch dependencies from `azure-cli-core` to `azure-cli` in next release, this will transient install it.
It's also installed with pytest, so that why I did not have the issue.

Thx for reporting!
