### ISSUE TITLE
Multi-tenant support

### ISSUE THREAD

**Issue by 0dragosh** [abij/az-account-switcher#5]
Hey!

I use az-switch and it works well for one tenant and multiple subscriptions, but with multiple tenants and multiple subscriptions (same in both tenants) you have to re-login.

For example:

```
                     Subscription A
                   /                   
Tenant 1 - 
                   \
                     Subscription B
```
```
                     Subscription A
                   /                   
Tenant 2 - 
                   \
                     Subscription B
```
I would love to be able to switch between Tenant1+SubA & Tenant2+SubB.

I know az cli itself doesn't have multi-tenant support, so maybe swap out `$HOME/.az` from under its feet?

Something like mv it to `$HOME/.az_tenant-id` and when the user selects a tenant & sub from `az-switch` it gets mv'd back to `$HOME/.az`?

**Comment by abij** [comment]
This can be a good and very useful improvement

Thats an awesome idea. This requires the user to setup the .azure folder correctly. In the end it's just a pointer to a folder. I think this can be done with an environment variable: `AZURE_CONFIG_DIR` looks like it. 

But how would the wrapper know about the different tenants?

I have to think about it, when I have some free time I'll play around with a couple of ideas.

**Comment by 0dragosh** [comment]
> This can be a good and very useful improvement
> 
> Thats an awesome idea. This requires the user to setup the .azure folder correctly. In the end it's just a pointer to a folder. I think this can be done with an environment variable: `AZURE_CONFIG_DIR` looks like it.

Great! Glad you like it.

> But how would the wrapper know about the different tenants?

Hmm, maybe time for a config file in `$XDG_CONFIG_HOME`?

> I have to think about it, when I have some free time I'll play around with a couple of ideas.

Awesome!

**Comment by abij** [comment]
Actually, I'm using multiple tenants with multiple subscriptions. But it's all tight to one account. (Azure login email). Do you mean multiple login-accounts?
